### ISSUE TITLE
[FR] Double tap the screen to lock the phone

### ISSUE THREAD

**Issue by hama73** [MrMannWood/launcher#23]
This feature goes with the two main core concept of the launcher, which is being fast and using shortcuts most of the time.
 It's very convenient to lock the phone with double tapping the screen and not to reach the power button every time. 

I have seen this feature in Samsung's “One UI” launcher and the open source [KISS launcher](https://github.com/Neamar/KISS) as an option.

What do you think?

**Comment by MrMannWood** [comment]
double tap + hold is already in use (to open settings). Also, there's already a hardware button on most devices that does this.

**Comment by mjray** [comment]
Please would you reconsider this decision? The hardware button is not a minimal interaction, because one has to pick up the phone else there is not enough resistance to push the button, plus the are other ways to access the settings menu, like from the menu that appears on holding on the top or bottom wheel shortcuts.

Double tap was my usual way of locking the device in my old launcher and I miss it because it's a really flowing way to end an interaction.

**Comment by arfanmrafeek** [comment]
For this to work, In my case, I have shortcut option in my settings, My phone Redmi note 10 pro 5G, There are options like this..
![Screenshot_2022-08-24-16-40-48-155_com android settings](https://user-images.githubusercontent.com/69381592/186404347-4c3a3cbc-cfc5-4024-8f53-ae602b406e88.jpg)
I think long press in menu is better, Because There will be internal conflict for this launcher, Because the launcher option (Settings, Widget, and change wallpaper) to work you need to double tap. This cause you not to open the option but turn your screen off. In my case I used to both double tap and long press menu. Hope this find helpful for you.

**Comment by mjray** [comment]
@arfanmrafeek - it doesn't seem helpful because my phone can have at most 3 buttons (back, home and recents) on screen, all of which have all their shortcuts allocated to useful things. The modern way is no buttons and gesture navigation. What current devices still have a screen menu button?
