### ISSUE TITLE
Date widget stuck in US format

### ISSUE THREAD

**Issue by mjray** [MrMannWood/launcher#28]
The Date widget seems to use a US format of "Day, Month DD" no matter what language I select (albeit with day and month names translated). Is it possible to get either UK ("Day DD Month") or ISO ("YYYY-MM-DD Day") format, through either system, app or widget settings?

**Comment by MrMannWood** [comment]
This is an issue, and one I hadn't considered. Time/Date formats are currently hardcoded. In their current form making them customizable is more difficult than it should be. Changing them to use arbitrary formats is a good idea, but I'd rather invest in supporting true widgets instead of continuing to work on this custom approach.
